# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'use_modular_headers' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  pod 'Alamofire'
  pod 'AFNetworking', :modular_headers => true

  # Pods for use_modular_headers

end
