# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swift_use_framework_static_linkage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks! :linkage => :static
  pod 'Alamofire'
  pod 'AFNetworking'
  # Pods for swift_use_framework_static_linkage

end
